export const US_STATE_NAME_MAP = {
  '01':	{ abbrev: "AL", name: "Alabama" },
  "02": { abbrev: "AK", name: "Alaska" },
  "04": { abbrev: "AZ", name: "Arizona" },
  "05": { abbrev: "AR", name: "Arkansas" },
  "06": { abbrev: "CA", name: "California" },
  "08": { abbrev: "CO", name: "Colorado" },
  "09": { abbrev: "CT", name: "Connecticut" },
  "10": { abbrev: "DE", name: "Delaware" },
  "11": { abbrev: "DC", name: "District of Columbia" },
  "12": { abbrev: "FL", name: "Florida" },
  "13": { abbrev: "GA", name: "Georgia" },
  "15": { abbrev: "HI", name: "Hawaii" },
  "16": { abbrev: "ID", name: "Idaho" },
  "17": { abbrev: "IL", name: "Illinois" },
  "18": { abbrev: "IN", name: "Indiana" },
  "19": { abbrev: "IA", name: "Iowa" },
  "20": { abbrev: "KS", name: "Kansas" },
  "21": { abbrev: "KY", name: "Kentucky" },
  "22": { abbrev: "LA", name: "Louisiana" },
  "23": { abbrev: "ME", name: "Maine" },
  "24": { abbrev: "MD", name: "Maryland" },
  "25": { abbrev: "MA", name: "Massachusetts" },
  "26": { abbrev: "MI", name: "Michigan" },
  "27": { abbrev: "MN", name: "Minnesota" },
  "28": { abbrev: "MS", name: "Mississippi" },
  "29": { abbrev: "MO", name: "Missouri" },
  "30": { abbrev: "MT", name: "Montana" },
  "31": { abbrev: "NE", name: "Nebraska" },
  "32": { abbrev: "NV", name: "Nevada" },
  "33": { abbrev: "NH", name: "New Hampshire" },
  "34": { abbrev: "NJ", name: "New Jersey" },
  "35": { abbrev: "NM", name: "New Mexico" },
  "36": { abbrev: "NY", name: "New York" },
  "37": { abbrev: "NC", name: "North Carolina" },
  "38": { abbrev: "ND", name: "North Dakota" },
  "39": { abbrev: "OH", name: "Ohio" },
  "40": { abbrev: "OK", name: "Oklahoma" },
  "41": { abbrev: "OR", name: "Oregon" },
  "42": { abbrev: "PA", name: "Pennsylvania" },
  "44": { abbrev: "RI", name: "Rhode Island" },
  "45": { abbrev: "SC", name: "South Carolina" },
  "46": { abbrev: "SD", name: "South Dakota" },
  "47": { abbrev: "TN", name: "Tennessee" },
  "48": { abbrev: "TX", name: "Texas" },
  "49": { abbrev: "UT", name: "Utah" },
  "50": { abbrev: "VT", name: "Vermont" },
  "51": { abbrev: "VA", name: "Virginia" },
  "53": { abbrev: "WA", name: "Washington" },
  "54": { abbrev: "WV", name: "West Virginia" },
  "55": { abbrev: "WI", name: "Wisconsin" },
  "56": { abbrev: "WY", name: "Wyoming" },
  "60": { abbrev: "AS", name: "America Samoa" },
  "64": { abbrev: "FM", name: "Federated States of Micronesia" },
  "66": { abbrev: "GU", name: "Guam" },
  "68": { abbrev: "MH", name: "Marshall Islands" },
  "69": { abbrev: "MP", name: "Northern Mariana Islands" },
  "70": { abbrev: "PW", name: "Palau" },
  "72": { abbrev: "PR", name: "Puerto Rico" },
  "74": { abbrev: "UM", name: "U.S. Minor Outlying Islands" },
  "78": { abbrev: "VI", name: "Virgin Islands of the United States" },
};
